# Generated by Django 5.2.7 on 2025-10-29 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0002_division_zone_profile_division_school_profile_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='Estimated project cost', max_digits=12)),
                ('project_type', models.CharField(choices=[('new_construction', 'New Construction'), ('repair', 'Repair')], max_length=30)),
                ('sponsor', models.CharField(blank=True, help_text='Funding source or sponsor name', max_length=200)),
                ('contractor', models.CharField(blank=True, help_text='Main contractor name', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user_app.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
