# Generated by Django 5.2.7 on 2025-10-30 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
        ('user_app', '0003_schooluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('progress', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='project_reports/')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='project_photos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects_app.projects')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.school')),
            ],
        ),
    ]
