# Generated by Django 5.2.7 on 2025-10-30 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_projectprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprogress',
            name='photos',
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_photos/')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='projects_app.projectprogress')),
            ],
        ),
    ]
