# Generated by Django 5.2.7 on 2026-03-28 04:10

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_projects_assigned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressphoto',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='project_photos/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='report_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='project_reports/'),
        ),
    ]
