# Generated by Django 5.2.7 on 2026-03-28 08:17

import cloudinary.models
import projects_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0005_alter_progressphoto_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressphoto',
            name='image',
            field=models.ImageField(upload_to='project_photos/'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='report_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[projects_app.models.validate_pdf]),
        ),
    ]
