# Generated by Django 5.2.7 on 2026-04-29 07:43

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0006_alter_progressphoto_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='progress',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='report_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
