# Generated by Django 5.2.7 on 2026-05-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0007_alter_progressphoto_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='ongoing', max_length=20),
        ),
    ]
